### ISSUE TITLE
Your ship fires phasers even after death.

### ISSUE THREAD

**Issue by coola** [unclebob/spacewar#9]
Moreover it can even kill enemy ship after its death :)

https://i.imgur.com/zQmZMBf.png

**Comment by unclebob** [comment]
Yeah, I know.  The ship actually still exists.  I just stop drawing it.  Care to fix that one?  Send me a pull request.

**Comment by coola** [comment]
Aye Aye Captain @unclebob!

I've fixed it in this pull request.
https://github.com/unclebob/spacewar/pull/10

Kindly please review the code :)

**Comment by coola** [comment]
Fixed with  05daef4a1116c3d8b3bf75746212e520b1e8a969
